language: python
python:
  - "3.8"
# Commande pour installer votre code
install:
  - pip install .
# Commandes pour installer les dépendances
before_script:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install pytest
  - pip install coveralls
# Commande pour exécuter les tests
script:
  - pytest --cov=tlearning
# Commande pour envoyer les résultats de couverture de code à coveralls.io
after_success:
  - coveralls